[build-system]
requires = [
    "setuptools>=71,<72; python_version < '3.9'",
    "setuptools>=77; python_version >= '3.9'",
    "wheel",
    "Cython>=3.1,<3.3",
]
build-backend = "setuptools.build_meta"

[project]
name = "py_upper"
version = "0.17.0"
description = "py_upper standalone Python application"
requires-python = ">=3.8,<3.14"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.py_upper]
entry = "main.py"

[tool.py_upper.app]
name = "MyApp"
identifier = "com.example.pyupper"

[tool.py_upper.runtime]
provider = "pbs"
python = "3.13.15"

[tool.py_upper.cython]
include = ["*"]
exclude = []

[tool.py_upper.optimize]
profile = "safe"
remove_python_caches = true
remove_tests = false
remove_docs = false
strip_native = false

[tool.py_upper.windows]
architectures = ["x86", "x86_64", "arm64"]

[tool.py_upper.macos]
architectures = ["arm64", "x86_64"]

[tool.py_upper.linux]
architectures = ["x86_64", "arm64"]
