from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import sysconfig
import tempfile
from pathlib import Path

import pytest

from py_upper.config import host_target
from py_upper.toolchain import resolve_toolchain


def _host_libpython() -> Path:
    """Locate the shared library of the interpreter running the tests.

    sysconfig describes two layouts. A normal build reports ``LIBDIR`` and
    ``LDLIBRARY`` as ``.../lib`` plus ``libpython3.13.so.1.0``. A macOS
    framework build reports ``LDLIBRARY`` as ``Python.framework/Versions/3.13/
    Python``, a path fragment that is not relative to ``LIBDIR`` at all, so
    joining the two describes a file that has never existed.
    """
    candidates: list[Path] = []
    libdir = sysconfig.get_config_var("LIBDIR")
    framework = sysconfig.get_config_var("PYTHONFRAMEWORK")
    if framework:
        version = sysconfig.get_config_var("PYTHONFRAMEWORKVERSION") or f"{sys.version_info.major}.{sys.version_info.minor}"
        prefix = sysconfig.get_config_var("PYTHONFRAMEWORKPREFIX")
        if prefix:
            candidates.append(Path(str(prefix)) / f"{framework}.framework" / "Versions" / str(version) / str(framework))
        # The framework that owns the libdir, and the framework that owns the
        # stdlib the fixture copies. They disagree on an interpreter whose
        # sysconfig was generated by a different Xcode than the one running.
        if libdir:
            candidates.append(Path(str(libdir)).parent / str(framework))
        candidates.append(Path(sysconfig.get_path("stdlib")).parent.parent / str(framework))
    if libdir:
        for name in (sysconfig.get_config_var("LDLIBRARY"), sysconfig.get_config_var("INSTSONAME")):
            if name and "/" not in str(name):
                candidates.append(Path(str(libdir)) / str(name))
        candidates.extend(sorted(Path(str(libdir)).glob("libpython3.*")))
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise RuntimeError("Host libpython not found; tried: " + ", ".join(str(path) for path in candidates))


def _make_local_runtime(repo: Path) -> str:
    """Build a local runtime + SDK fixture from the running interpreter.

    The fixture mirrors the directory layout of a downloaded PBS runtime so the
    full build chain (runtime manifest, launcher, Cython extensions, packaging,
    target smoke) can be exercised without network access. Windows keeps the
    python.exe + Lib/ + DLLs/ layout; Unix keeps bin/ + lib/pythonX.Y.
    """
    target = host_target()
    version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    major_minor = f"{sys.version_info.major}.{sys.version_info.minor}"
    digits = f"{sys.version_info.major}{sys.version_info.minor}"
    runtime = repo / "runtimes" / target.key / version
    sdk = repo / "build" / "e2e-sdk" / target.key / version
    for path in (runtime, sdk):
        if path.exists():
            shutil.rmtree(path)
    runtime.mkdir(parents=True)
    (sdk / "bin").mkdir(parents=True)
    (sdk / "include").mkdir(parents=True)

    stdlib = Path(sysconfig.get_path("stdlib"))
    ignore = shutil.ignore_patterns("site-packages", "__pycache__")

    if target.os == "windows":
        shutil.copyfile(sys.executable, runtime / "python.exe")
        for dll in Path(sys.executable).parent.glob(f"python{digits}.dll"):
            shutil.copyfile(dll, runtime / dll.name)
        shutil.copytree(stdlib, runtime / "Lib", symlinks=True, ignore=ignore)
        extension_dir = Path(sysconfig.get_path("platstdlib")).parent / "DLLs"
        if extension_dir.is_dir():
            shutil.copytree(extension_dir, runtime / "DLLs", symlinks=True, ignore=ignore)
        executable_name = "python.exe"
    else:
        (runtime / "bin").mkdir()
        (runtime / "lib").mkdir()
        executable = runtime / "bin" / f"python{major_minor}"
        if target.os == "macos":
            # A framework interpreter cannot be relocated by copying it: the
            # launcher stub resolves its libpython relative to its own path
            # (Xcode Command Line Tools uses @executable_path/../Python3) or
            # re-execs the app bundle next to the library it loaded, so the copy
            # dies in dyld before Python starts. Link to the host interpreter
            # instead. The bundled libpython below is what the packaged launcher
            # loads, and PYTHONHOME still points the target smoke at the
            # fixture's own stdlib and staged packages.
            executable.symlink_to(Path(sys.executable).resolve())
        else:
            shutil.copyfile(sys.executable, executable)
            executable.chmod(0o755)
        # The launcher looks for a PBS-shaped libpython (libpython3.X.dylib /
        # libpython3.X.so) in runtime/lib, so a framework build's bare
        # "Python" filename must be renamed on the way in.
        suffix = ".dylib" if target.os == "macos" else ".so"
        shutil.copyfile(_host_libpython(), runtime / "lib" / f"libpython{major_minor}{suffix}")
        shutil.copytree(stdlib, runtime / "lib" / f"python{major_minor}", symlinks=True, ignore=ignore)
        executable_name = f"python{major_minor}"

    shutil.copyfile(runtime / ("python.exe" if target.os == "windows" else f"bin/{executable_name}"), sdk / "bin" / executable_name)
    shutil.copytree(Path(sysconfig.get_path("include")), sdk / "include" / f"python{major_minor}", symlinks=True, ignore=ignore)

    manifest = {
        "format": 4,
        "provider": "local",
        "target": target.key,
        "target_triple": target.triple,
        "python": version,
        "python_major_minor": major_minor,
        "python_abi": f"cp{digits}",
        "python_platform_tag": target.primary_wheel_platform,
        "python_implementation": "cpython",
        "runtime": {"root": "."},
        "sdk": {"root": "configured"},
        "python_executable": f"bin/{executable_name}",
        "include_dir": f"include/python{major_minor}",
    }
    (runtime / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return version


def _compiler_environment(target) -> dict[str, str]:
    env = dict(os.environ)
    env.update(resolve_toolchain(target).env)
    return env


def _make_app_native_tree(repo: Path, target) -> None:
    """Application-owned native libraries that depend on each other."""
    native = repo / "app" / "src" / "config"
    native.mkdir(parents=True, exist_ok=True)
    env = _compiler_environment(target)
    if target.os == "windows":
        cc = shutil.which("cl", path=env.get("PATH"))
        if not cc:
            pytest.skip("cl.exe is required to build the app-native DLL fixture")
        child_c = native / "child.c"
        parent_c = native / "parent.c"
        child_c.write_text("__declspec(dllexport) int demo_child(void) { return 7; }\n", encoding="utf-8")
        parent_c.write_text(
            "__declspec(dllimport) int demo_child(void);\n__declspec(dllexport) int demo_parent(void) { return demo_child(); }\n",
            encoding="utf-8",
        )
        subprocess.run([cc, "/nologo", "/LD", "/O2", str(child_c), "/Fe:" + str(native / "demo_child.dll"), "/Fo:" + str(native / "child.obj")], check=True, cwd=repo, env=env)
        subprocess.run([cc, "/nologo", "/LD", "/O2", str(parent_c), "/Fe:" + str(native / "demo_parent.dll"), "/Fo:" + str(native / "parent.obj"), "/link", "/LIBPATH:" + str(native), "demo_child.lib"], check=True, cwd=repo, env=env)
        for leftover in native.glob("*.obj"):
            leftover.unlink()
        return

    cc = shutil.which("clang") or shutil.which("gcc") or shutil.which("cc")
    if not cc:
        pytest.skip("a host C compiler is required for the app-native fixture")
    child_c = native / "child.c"
    parent_c = native / "parent.c"
    child_c.write_text("int demo_child(void) { return 7; }\n", encoding="utf-8")
    parent_c.write_text("extern int demo_child(void); int demo_parent(void) { return demo_child(); }\n", encoding="utf-8")
    if target.os == "macos":
        child, parent = native / "libdemo_child.dylib", native / "libdemo_parent.dylib"
        subprocess.run([cc, "-dynamiclib", "-O2", str(child_c), "-install_name", "@rpath/libdemo_child.dylib", "-o", str(child)], check=True, cwd=repo)
        subprocess.run([cc, "-dynamiclib", "-O2", str(parent_c), "-L", str(native), "-ldemo_child", "-install_name", "@rpath/libdemo_parent.dylib", "-o", str(parent)], check=True, cwd=repo)
    else:
        child, parent = native / "libdemo_child.so", native / "libdemo_parent.so"
        subprocess.run([cc, "-shared", "-fPIC", "-O2", str(child_c), "-o", str(child)], check=True, cwd=repo)
        subprocess.run([cc, "-shared", "-fPIC", "-O2", str(parent_c), "-L", str(native), "-ldemo_child", "-Wl,-rpath,$ORIGIN", "-o", str(parent)], check=True, cwd=repo)
    child_c.unlink()
    parent_c.unlink()


def _make_test_wheels(repo: Path) -> Path:
    from test_third_party import make_native_wheel, make_wheel

    target = host_target()
    wheel_dir = repo / "build" / "e2e-wheelhouse"
    if wheel_dir.exists():
        shutil.rmtree(wheel_dir)
    wheel_dir.mkdir(parents=True, exist_ok=True)
    make_wheel(wheel_dir, requires_dist="demo-native==1.0.0")
    # The packaged application imports this wheel, so it has to be built for the
    # host architecture and tagged with the host platform: a wheel compiled for
    # another architecture would only surface at the very end of the build.
    make_native_wheel(wheel_dir, platform_tag=target.primary_wheel_platform)
    return wheel_dir


def _prepare_repo() -> Path:
    source_repo = Path(__file__).parents[2]
    temp_root = Path(tempfile.mkdtemp(prefix="py-upper-e2e-"))
    repo = temp_root / "repo"
    shutil.copytree(
        source_repo,
        repo,
        ignore=shutil.ignore_patterns(".git", ".cache", "build", "dist", "runtimes", "__pycache__", ".pytest_cache"),
        symlinks=True,
    )
    version = _make_local_runtime(repo)
    wheel_dir = _make_test_wheels(repo)

    pyproject = repo / "app" / "pyproject.toml"
    project = pyproject.read_text(encoding="utf-8")
    start = project.index("[tool.py_upper.runtime]")
    end = project.index("[tool.py_upper.dependencies]")
    project = project[:start] + (
        "[tool.py_upper.runtime]\n"
        'provider = "local"\n'
        f'python = "{version}"\n'
        'runtime = "runtimes/{target}/{python}"\n'
        'sdk = "build/e2e-sdk/{target}/{python}"\n\n'
    ) + project[end:]
    # Only the wheel source is injected: everything else in the section stays
    # as configured, because the fixture wheel must satisfy the same resolver
    # configuration the build reads. Rewriting the whole section used to drop
    # the manylinux baselines, so the fixture wheel kept the host's tag while
    # the build resolved the fallback baseline, and pip rejected the wheel.
    project, injected = re.subn(
        r"^\[tool\.py_upper\.dependencies\]\n",
        lambda match: match.group(0) + f'find_links = ["{wheel_dir.relative_to(repo).as_posix()}"]\nno_index = true\n',
        project,
        count=1,
        flags=re.M,
    )
    assert injected == 1, "app/pyproject.toml must declare [tool.py_upper.dependencies]"
    project, replaced = re.subn(
        # Anchor to the start of the line: a commented-out example of the key
        # must never win over the declaration that is actually in effect.
        r"^dependencies = \[[^\]]*\]",
        'dependencies = ["demo-pkg==1.0.0", "demo-native==1.0.0"]',
        project,
        count=1,
        flags=re.M,
    )
    assert replaced == 1, "could not rewrite [project].dependencies in the E2E fixture"
    pyproject.write_text(project, encoding="utf-8")

    main_py = repo / "app" / "src" / "main.py"
    main_py.write_text(
        "from core.app import run_application\n"
        "import demo_native\n"
        "import demo_pkg\n\n\n"
        "def main() -> None:\n"
        '    assert demo_pkg.VALUE == "ok"\n'
        "    assert demo_native.value() == 42\n"
        "    run_application()\n\n\n"
        'if __name__ == "__main__":\n'
        "    main()\n",
        encoding="utf-8",
    )
    return temp_root


def _run_build(repo: Path, *args: str) -> subprocess.CompletedProcess:
    env = dict(os.environ)
    env["PY_UPPER_PYTHON"] = sys.executable
    env["PY_UPPER_E2E"] = "1"
    # --run must not wait for a window server.
    env["PY_UPPER_HEADLESS"] = "1"
    return subprocess.run(
        [sys.executable, "tools/build.py", *args],
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )


def _packaged_root(repo: Path, target) -> Path:
    if target.os == "macos":
        return repo / "dist" / "MyApp.app" / "Contents" / "Resources"
    return repo / "dist" / "MyApp"


@pytest.mark.skipif(os.environ.get("PY_UPPER_E2E") != "1", reason="set PY_UPPER_E2E=1 to run the full local build E2E")
def test_local_build_end_to_end_with_third_party_dependency():
    target = host_target()
    temp_root = _prepare_repo()
    try:
        repo = temp_root / "repo"
        result = _run_build(repo, "--run", "--target", target.key)
        assert result.returncode == 0, result.stdout + "\n" + result.stderr
        assert "SMOKE PASS launcher" in result.stdout
        assert "Hello from py_upper" in result.stdout
        # The Qt window is gated by the integration run, which builds the real
        # dependency set; this fixture application has no PySide6.

        packaged = _packaged_root(repo, target) / "site-packages"
        assert (packaged / "demo_pkg" / "__init__.py").exists()
        extension = ".pyd" if target.os == "windows" else ".so"
        assert any(path.name.startswith("demo_native") and path.suffix == extension for path in packaged.iterdir())
        assert not (packaged / "main.py").exists()

        wheel_manifest = json.loads((repo / "build" / "wheels" / target.key / "manifest.json").read_text(encoding="utf-8"))
        assert sorted(wheel_manifest["requirements"]) == ["demo-native==1.0.0", "demo-pkg==1.0.0"]
        wheel_names = {item["file"] for item in wheel_manifest["wheels"]}
        assert any(name.startswith("demo_pkg-") for name in wheel_names)
        assert any(name.startswith("demo_native-") for name in wheel_names)
        assert sorted(wheel_manifest["imports"]) == ["demo_native", "demo_pkg"]

        # lock / --locked round trip: the lock file must be the authority for
        # runtime, SDK and wheel inputs without re-resolving anything.
        lock = _run_build(repo, "--lock", "--target", target.key)
        assert lock.returncode == 0, lock.stdout + "\n" + lock.stderr
        assert (repo / "py_upper.lock.json").exists()
        locked = _run_build(repo, "--locked", "--target", target.key)
        assert locked.returncode == 0, locked.stdout + "\n" + locked.stderr
    finally:
        shutil.rmtree(temp_root, ignore_errors=True)


@pytest.mark.skipif(os.environ.get("PY_UPPER_E2E") != "1", reason="set PY_UPPER_E2E=1 to run the full local build E2E")
def test_local_build_embeds_application_owned_native_libraries():
    """Application-owned libraries must resolve their own dependency closure."""
    target = host_target()
    temp_root = _prepare_repo()
    try:
        repo = temp_root / "repo"
        _make_app_native_tree(repo, target)
        result = _run_build(repo, "--run", "--target", target.key)
        assert result.returncode == 0, result.stdout + "\n" + result.stderr
        assert "Hello from py_upper" in result.stdout

        site = _packaged_root(repo, target) / "site-packages"
        bundled = sorted(path.name for path in (site / "config").iterdir())
        # The fixture builds one shared library per host, so the bundled names
        # follow the host's convention rather than a single hard-coded one.
        if target.os == "windows":
            expected = ("demo_parent.dll", "demo_child.dll")
        elif target.os == "macos":
            expected = ("libdemo_parent.dylib", "libdemo_child.dylib")
        else:
            expected = ("libdemo_parent.so", "libdemo_child.so")
        assert all(name in bundled for name in expected), bundled

        report = json.loads((repo / "build" / "native-deps" / target.key / "report.json").read_text(encoding="utf-8"))
        assert report, "native dependency report must not be empty"
        assert not [item for item in report if item["unresolved"]], report
    finally:
        shutil.rmtree(temp_root, ignore_errors=True)
